seleccionar_variables <- function(data) {
    # Por ahora no consideraremos algunas variables de texto,
    # seleccionaremos las variables que consideramos más
    # útiles para nuestro objetivo
    df <- data %>% select(
        id,
        last_scraped,
        name,
        host_id,
        host_name,
        host_since,
        host_response_time,
        host_response_rate,
        host_acceptance_rate,
        host_is_superhost,
        host_total_listings_count,
        host_verifications,
        host_identity_verified,
        neighbourhood,
        neighbourhood_cleansed,
        neighbourhood_group_cleansed,
        latitude,
        longitude,
        property_type,
        room_type,
        accommodates,
        bathrooms,
        # bathrooms_text,
        bedrooms,
        beds,
        amenities,
        price,
        minimum_nights,
        maximum_nights,
        minimum_minimum_nights,
        maximum_minimum_nights,
        minimum_maximum_nights,
        maximum_maximum_nights,
        minimum_nights_avg_ntm,
        maximum_nights_avg_ntm,
        calendar_updated,
        has_availability,
        availability_30,
        availability_60,
        availability_90,
        availability_365,
        calendar_last_scraped,
        number_of_reviews,
        number_of_reviews_ltm,
        # number_of_reviews_l30d,
        first_review,
        last_review,
        review_scores_rating,
        review_scores_accuracy,
        review_scores_cleanliness,
        review_scores_checkin,
        review_scores_communication,
        review_scores_location,
        review_scores_value,
        license,
        instant_bookable,
        calculated_host_listings_count
    )

    return(df)
}