setwd("./proyecto")
library(dplyr)
library(tidyr)
data <- read.csv('listings.csv', encoding='UTF-8')
data1 <- data %>% select(id, last_scraped,host_id, host_name, host_since, host_response_time, host_response_rate, host_acceptance_rate, host_is_superhost, host_total_listings_count, host_verifications, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, latitude, longitude, property_type, room_type, accommodates, bathrooms, bathrooms_text, bedrooms, beds,  amenities, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm)
data1 <- data1 %>% mutate(last_scraped = as.Date(last_scraped, "%Y-%m-%d"), host_since = as.Date(host_since, "%Y-%m-%d"), host_since = as.Date(host_since, "%Y-%m-%d"))
data1 <- data1 %>% mutate(host_response_rate = gsub("\\%", "", host_response_rate), host_acceptance_rate = gsub("\\%", "", host_acceptance_rate), price = gsub("\\$", "", price))
data1 <- data1 %>% mutate(host_response_rate = as.numeric(host_response_rate)/100, host_acceptance_rate = as.numeric(host_acceptance_rate)/100, price = as.numeric(price))
data1 <- data1 %>% mutate(host_is_superhost = factor(host_is_superhost, levels=c('t', 'f'), labels=c(1, 0)), host_identity_verified = factor(host_identity_verified, levels=c('t', 'f'), labels=c(1, 0)))
View(data1)
str(data1)
